titles:
  en: "Status: { .status }"
  es: "Estado: { .status }"
  fr: "Statut: { .status }"
  de: "Status: { .status }"
  ru: "Статус: { .status }"
order_by: $last_modified desc
formats:
  - md
columns:
  - title:
  - tags:
