titles:
  en: Tasks
  ru: Задачи
record_file:
  name: "$records/{key}.json"
  type: "[]map[string]any"
  format: json
data_dir: $records
columns:
  title:
    type: string
    titles:
      en: Task
      ru: Задача
      es: Tarea
      fr: Tâche
      de: Aufgabe
    required: true
    max_length: 100
  status:
    type: string
    required: true
    titles:
      en: Status
      ru: Статус
      es: Estado
      fr: Statut
      de: Status
    foreign_key: statuses
columns_order:
  - title
  - status
